### ISSUE TITLE
Every Game Crashing Playdate

### ISSUE THREAD

**Issue by corsair** [adamsoutar/playboy#4] opened 2022-07-02 04:51 UTC
Hello Adam,

First and foremost, thank you for your time and contributions towards this!

I just got my Playdate and promptly got this loaded onto it, however upon launching **any** ROM, it will result in an immediate crash with the Playdate staing "Sorry, your Playdate has crashed. Press (A) to restart."

I am on the latest build of Playboy and can provide any other details (or crash logs if those exist somewhere).

Update: This appears in the "Console" when my Playdate is connected to the Simulator.

```
time and date set
Loading game ""
Extra chips: None
ROM size: 32KB
RAM size: 0KB
Unsupported memory write at 0xff61 (value: 0xff)
Unsupported memory write at 0xff61 (value: 0xff)
Unsupported memory write at 0xff71 (value: 0x71)
```

**Comment by adamsoutar** [comment] 2022-09-04 21:57
Hey dude, sorry I totally missed this issue - don't know how I did!

If you didn't resolve this issue in the end, would you mind providing some more detail?

Are you copying your games over from a Mac or a Windows machine? There are strange little quirks, like when you copy a file named `game.gb` from a Mac to a Playdate, Finder creates a second file called `._game.gb`. This second file is not a real ROM and Playboy will fail to load it.

Also, could you detail which games you're trying to play?

It looks like the ROM file is not being read correctly (hence its name is `""`). This will also happen if you directly try to play a `.zip` file you got from a ROM site, instead of first extracting the raw `.gb` file from it.

**Comment by adamsoutar** [comment] 2023-07-09 01:29
Closing as old and unreproducible, lmk if you see this again

**Closed by adamsoutar** 2023-07-09 01:29 UTC
